//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bernoulli.h
//  @ Date : 19.03.2018
//  @ Author :
//
//


#if !defined(_BERNOULLI_H)
#define _BERNOULLI_H

#include "Newton.h"
#include "Power.h"

class Bernoulli
{
public:
    float getValue();
    void setK(int k);
    void setN(int n);
    void setP(float p);
    Bernoulli(int k, int n, float p);
private:
    Newton newton;
    Power pk;
    Power qnk;
    int k;
    int n;
    float p;
    float value;
    void calculate();
};

#endif  //_BERNOULLI_H
