//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Factorial.cpp
//  @ Date : 19.03.2018
//  @ Author :
//
//


#include "Factorial.h"

int Factorial::getValue()
{
    calculate();
    return value;
}

void Factorial::setN(int n)
{
    this->n = n;
}


void Factorial::calculate()
{
    value = 1;
    for(int i = 1; i <= n; ++i)
        value *= i;
}

