//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Factorial.h
//  @ Date : 19.03.2018
//  @ Author :
//
//


#if !defined(_FACTORIAL_H)
#define _FACTORIAL_H


class Factorial
{
public:
    int getValue();
    void setN(int n);
private:
    int n;
    int value;
    void calculate();
};

#endif  //_FACTORIAL_H
