//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Newton.cpp
//  @ Date : 19.03.2018
//  @ Author :
//
//


#include "Newton.h"

int Newton::getValue()
{
    calculate();
    return value;
}

void Newton::setN(int n)
{
    this->n = n;
}

void Newton::setK(int k)
{
    this->k = k;
}

void Newton::calculate()
{
    fact_n.setN(n);
    fact_nk.setN(n-k);
    fact_k.setN(k);
    value = fact_n.getValue()/(fact_nk.getValue() * fact_k.getValue());
}

