//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Newton.h
//  @ Date : 19.03.2018
//  @ Author :
//
//


#if !defined(_NEWTON_H)
#define _NEWTON_H

#include "Factorial.h"

class Newton
{
public:
    int getValue();
    void setN(int n);
    void setK(int k);
private:
    Factorial fact_n;
    Factorial fact_nk;
    Factorial fact_k;
    int n;
    int k;
    int value;
    void calculate();
};

#endif  //_NEWTON_H
