//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Power.h
//  @ Date : 19.03.2018
//  @ Author :
//
//


#if !defined(_POWER_H)
#define _POWER_H


class Power
{
public:
    float getValue();
    void setBase(float b);
    void setExponent(int e);
private:
    float base;
    int exponent;
    float value;
    void calculate();
};

#endif  //_POWER_H
