//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Power.cpp
//  @ Date : 19.03.2018
//  @ Author :
//
//


#include "Power.h"

float Power::getValue()
{
    calculate();
    return value;
}

void Power::setBase(float b)
{
    base = b;
}

void Power::setExponent(int e)
{
    exponent = e;
}

void Power::calculate()
{
    int n = exponent;
    value = 1;
    while(n--)
        value *= base;
}

