//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TBook.h
//  @ Date : 05.03.2018
//  @ Author :
//
//


#if !defined(_TBOOK_H)
#define _TBOOK_H

#include <string>
using namespace std;

class TBook
{
public:
    TBook();
    ~TBook();
    void setTitle(string title);
    string getTitle();
    void setShelfMark(string mark);
    string getShelfMark();
private:
    string bookTitle;
    string shelfMark;
};

#endif  //_TBOOK_H
