//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TLibrary.cpp
//  @ Date : 05.03.2018
//  @ Author :
//
//


#include "TLibrary.h"

#include <iostream>

TLibrary::TLibrary(string libName)
{
    libraryName = libName;
    book = new TBook();
}

TLibrary::~TLibrary()
{
    delete book;
}

void TLibrary::printData()
{
    cout << book->getTitle() << " " << book->getShelfMark();
}

void TLibrary::setData(string title, string mark)
{
    book->setTitle(title);
    book->setShelfMark(mark);
}

