//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TStudent.cpp
//  @ Date : 05.03.2018
//  @ Author :
//
//


#include "TStudent.h"

void TStudent::setName(string name)
{
    studentName = name;
}

string TStudent::getName()
{
    return studentName;
}

void TStudent::setAge(int age)
{
    studentAge = age;
}

int TStudent::getAge()
{
    return studentAge;
}

